version: "3.2"
services:
  web:
    build:
      context: './compose/'
      args:
       PYTHON_VERSION: ${PYTHON_VERSION}
    networks:
      - frontend
      - backend
    ports:
      - "6444:80"
    volumes:
      - ${PROJECT_ROOT}/data/:/epics/
    container_name: epics
networks:
  frontend:
  backend:
volumes:
  data:
